clear  Complispe                       
clear  DNAmatrix1                      
clear  DNAmatrix2                      
clear  Num                             
clear  Ref                             
clear  Tmpref                          
clear  ans                             
%clear  cleanspenamelist                
clear  cleantemp1                      
clear  cleantemp2                      
clear  fid                             
clear  i                               
clear  indexAll                        
%clear  indexNonsingletons              
%clear  indexSingletons                 
clear  j                               
clear  k                               
clear  k2                              
clear  k3                              
clear  k4                              
clear  lengthIN                        
clear  lengthIS                        
clear  listSingletons                  
clear  m2                              
clear  m5                              
%clear  mydatabase                      
clear  n2                              
clear  n4                              
%clear  nRep                            
clear  nspecies                        
clear  out2                            
clear  popsize                         
%clear  r1                              
%clear  r2                              
clear  tmpAll                          
